trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: 'Production Settings'

stages:
  - stage: Build

    jobs: 
    - job : Build
    
      steps:
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'SonarCloud'
          organization: 'jannotjarks'
          scannerMode: 'MSBuild'
          projectKey: 'JannoTjarks_E-Paper'
          projectName: 'E-Paper'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          feedsToUse: 'select'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'

      - task: SonarCloudAnalyze@1

      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '--output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: false
          
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
    