trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build

    jobs: 
    - job : Build
    
      steps:
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'SonarCloud'
          organization: 'jannotjarks'
          scannerMode: 'MSBuild'
          projectKey: 'JannoTjarks_E-Paper'
          projectName: 'E-Paper'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          feedsToUse: 'select'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'

      - task: SonarCloudAnalyze@1

      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '--output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: false
          
      - task: CopyFiles@2
        inputs:
          Contents: 'Dockerfile'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/s'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
  
  - stage: Deploy

    jobs:
      - deployment: Production
        displayName: Production
        environment: Production
      
        variables:        
          - group: production-settings
        
        strategy:
            runOnce:
                deploy:                  
                    steps:
                    - task: SSH@0
                      displayName: 'Stop Service e-paper-api'
                      inputs:
                        sshEndpoint: 'root@jtjarks.de'
                        commands: 'systemctl stop e-paper-api.service'
                    
                    - task: FileTransform@2
                      displayName: "Transform Json"
                      inputs:
                        folderPath: '/home/vsts/work/1/drop/s/'
                        xmlTransformationRules: ''
                        jsonTargetFiles: 'appsettings.json'
                    - task: CopyFilesOverSSH@0
                      displayName: 'Securely copy files to the remote machine'
                      inputs:
                        sshEndpoint: 'root@jtjarks.de'
                        sourceFolder: '/home/vsts/work/1/drop/s/'
                        targetFolder: '/opt/e-paper-api/'
                        cleanTargetFolder: true
                      
                    - task: CmdLine@2
                      inputs:
                        script: |
                          ls -la /home/vsts/work/1/drop/
                          ls -la /home/vsts/work/1/drop/s/
                    - task: Docker@2
                      inputs:
                        containerRegistry: 'DockerHub'
                        repository: 'jannotjarks/e-paper-api'
                        command: 'buildAndPush'
                        Dockerfile: '/home/vsts/work/1/drop/Dockerfile'                        
                        tags: |
                          $(Build.BuildId)
                          latest
                        
                    - task: SSH@0
                      displayName: 'Start Service e-paper-api'
                      inputs:
                        sshEndpoint: 'root@jtjarks.de'
                        commands: 'systemctl start e-paper-api.service'

